In [1]:
import numpy as np
import pandas as pd

social = pd.read_csv("D:/Imarticus/DSP17/Python/Social_Network_Ads.csv")

In [2]:
social.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
import matplotlib.pyplot as plt

x = social.iloc[:, [2,3]].values
y = social.iloc[:, 4].values

In [4]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [5]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [6]:
#Fitting K-NN to the Training Set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p =2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [7]:
y_pred = classifier.predict(x_test)

In [8]:
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.93


In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[64,  4],
       [ 3, 29]], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

logit_model = LogisticRegression()
logit_model.fit(x_train,y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
pred = logit_model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred))

[[65  3]
 [ 8 24]]


In [13]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100



In [14]:
print("Accuracy:", metrics.accuracy_score(y_test, pred))

Accuracy: 0.89


In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly')
classifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
predictions = classifier.predict(x_test)

In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

[[67  1]
 [13 19]]


In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.84      0.99      0.91        68
           1       0.95      0.59      0.73        32

    accuracy                           0.86       100
   macro avg       0.89      0.79      0.82       100
weighted avg       0.87      0.86      0.85       100



In [20]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, predictions))

0.86


In [21]:
#Attained 93% accuracy using KNN classification algorithm